
name: 'jaffle_shop'
version: '0.1'
profile: 'jaffle_shop'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

seeds:
  jaffle_shop:
    enabled: true
    schema: raw

models:
  jaffle_shop:
      staging:
        materialized: view
        schema: staging
        tags: ["staging", "hourly"]
      marts:
        core:
          materialized: table
          schema: analysis
          intermediate:
            materialized: table
            schema: ods
          